import Head from "next/head";
import Link from "next/link";

const examples = [
  {
    name: "简单钱包",
    description:
      "使用 ethers.js 连接 Metamask，实现了连接、断开、查询余额、刷新余额、转账等加密钱包的极简功能。麻雀虽小，五脏俱全。适合初学者学习。",
    url: "/sample-wallet",
    technologyStack: [
      "next.js",
      "react",
      "tailwindcss",
      "headless-ui",
      "ethers.js",
    ],
  },
  {
    name: "Noah 代币",
    description:
      "基于 ERC20 协议实现的 Noah 代币。实现了 ERC20 的所有功能。包含了代币的发行、转账、查询余额、查询总量、授权、授权转账等功能。适合全栈开发者学习。",
    url: "/noah-token",
    technologyStack: [
      "next.js",
      "react",
      "tailwindcss",
      "chakra-ui",
      "wagmi",
      "solidity",
      "truffle",
      "ganache",
    ],
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello Web3!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center w-screen h-screen bg-[url(/bg.jpg)] p-20">
        <div className="flex flex-col w-full h-full gap-8 p-8 overflow-auto shadow-inner rounded-3xl backdrop-opacity-40 backdrop-invert">
          <div className="w-full text-3xl font-bold text-white">
            Web3 代码示例
          </div>
          <div className="grid grid-cols-4 gap-4">
            {examples.map(({ name, description, url, technologyStack }) => (
              <div
                key={name}
                className="flex flex-col gap-4 p-4 text-white transition-all duration-200 ease-in-out border-white rounded-md hover:border"
              >
                <Link className="text-2xl" href={url}>
                  {name}
                </Link>
                <div className="text-sm ">{description}</div>
                <div className="text-sm font-bold">技术栈</div>
                <ul>
                  {technologyStack.map((tech) => (
                    <li key={"tech"}>{tech}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
