import Head from "next/head";
import Link from "next/link";
import examples from "../examples.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello Web3!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center w-screen h-screen bg-[url(/bg.jpg)] p-20">
        <div className="flex flex-col w-full h-full gap-8 p-8 overflow-auto shadow-inner rounded-3xl backdrop-opacity-40 backdrop-invert">
          <div className="w-full text-3xl font-bold text-white">
            Web3 代码示例
          </div>
          <div className="grid grid-cols-4 gap-4">
            {examples.map(({ name, description, url, technologyStack }) => (
              <div
                key={name}
                className="flex flex-col gap-4 p-4 text-white transition-all duration-200 ease-in-out border-white rounded-md hover:border"
              >
                <Link className="text-2xl" href={url}>
                  {name}
                </Link>
                <div className="text-sm ">{description}</div>
                <div className="text-sm font-bold">技术栈</div>
                <ul>
                  {technologyStack.map((tech) => (
                    <li key={"tech"}>{tech}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
